site_name: Airton
repo_url: https://github.com/MarcoAAlmeida/airton

docs_dir: content

nav:
  - Home: index.md
  - Architecture: architecture.md

theme:
  name: material
  palette:
    primary: yellow

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
